import { useState } from 'react';
import styles from '../../styles/Admin.module.css';
import { useData } from '../../store/DataContext.jsx';
import HomeEditor from './HomeEditor.jsx';
import AboutEditor from './AboutEditor.jsx';
import PortfolioEditor from './PortfolioEditor.jsx';
import CollectionsManager from './CollectionsManager.jsx';
import ProjectsManager from './ProjectsManager.jsx';

const AdminPanel = () => {
  const {
    data,
    updateHome,
    updateAbout,
    updatePortfolio,
    addCollection,
    updateCollection,
    removeCollection,
    addProject,
    updateProject,
    removeProject,
    logout,
    resetData,
    setPassword,
    createId,
    replaceData
  } = useData();

  const [password, setPasswordInput] = useState('');
  const [passwordSaved, setPasswordSaved] = useState(false);
  const [importMessage, setImportMessage] = useState('');
  const fileInputId = 'content-import-file';

  const handleExportJson = () => {
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'site-data.json';
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleExportJsModule = () => {
    const jsModule = `// Generated by Admin export. Edits will be bundled.\nexport const defaultData = ${JSON.stringify(data, null, 2)};\n\nexport const getDefaultData = () => JSON.parse(JSON.stringify(defaultData));\n`;
    const blob = new Blob([jsModule], { type: 'application/javascript' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'defaultData.js';
    a.click();
    URL.revokeObjectURL(url);
  };

  const validateImported = (obj) => {
    if (!obj || typeof obj !== 'object') return 'Invalid file contents.';
    const requiredTop = ['home', 'about', 'portfolio', 'collections', 'projects', 'settings'];
    for (const key of requiredTop) {
      if (!(key in obj)) return `Missing top-level key: ${key}`;
    }
    if (!Array.isArray(obj.collections)) return 'collections must be an array';
    if (!Array.isArray(obj.projects)) return 'projects must be an array';
    return null;
  };

  const handleImportJson = async (file) => {
    setImportMessage('');
    try {
      const text = await file.text();
      const parsed = JSON.parse(text);
      const error = validateImported(parsed);
      if (error) {
        setImportMessage(error);
        return;
      }
      replaceData(parsed);
      setImportMessage('Imported content successfully.');
    } catch (err) {
      setImportMessage('Failed to import JSON.');
    }
  };

  const handlePasswordSubmit = (event) => {
    event.preventDefault();
    if (!password.trim()) return;
    setPassword(password.trim());
    setPasswordInput('');
    setPasswordSaved(true);
    window.setTimeout(() => setPasswordSaved(false), 2500);
  };

  const handleReset = () => {
    const confirmReset = window.confirm(
      'Reset all content back to the original sample data? This will clear any edits you have made.'
    );
    if (confirmReset) {
      resetData();
    }
  };

  return (
    <section className={styles.adminShell}>
      <header className={styles.headerRow}>
        <div>
          <p className={styles.inlineBadge}>Admin</p>
          <h1 className={styles.headerTitle}>Coral Dias backend</h1>
        </div>
        <div className={styles.headerActions}>
          <button type="button" className={styles.secondaryButton} onClick={handleReset}>
            Reset to defaults
          </button>
          <button type="button" className={styles.primaryButton} onClick={logout}>
            Sign out
          </button>
        </div>
      </header>

      <HomeEditor home={data.home} onSave={updateHome} />

      <AboutEditor about={data.about} onSave={updateAbout} onCreateId={createId} />

      <PortfolioEditor portfolio={data.portfolio} onSave={updatePortfolio} />

      <CollectionsManager
        collections={data.collections}
        projects={data.projects}
        onAddCollection={() => addCollection({})}
        onUpdateCollection={updateCollection}
        onRemoveCollection={removeCollection}
      />

      <ProjectsManager
        projects={data.projects}
        collections={data.collections}
        onAddProject={addProject}
        onUpdateProject={updateProject}
        onRemoveProject={removeProject}
        onCreateId={createId}
      />

      <div className={styles.panelCard}>
        <h2 className={styles.panelTitle}>Content data</h2>
        <p className={styles.panelDescription}>
          Changes are saved to this browser only. Export to JSON for backup, or export a JS module to replace
          <code> frontend/src/data/defaultData.js</code> for a full-site publish.
        </p>
        {importMessage ? <p className={styles.note}>{importMessage}</p> : null}
        <div className={styles.buttonRow}>
          <button type="button" className={styles.secondaryButton} onClick={handleExportJson}>
            Export JSON
          </button>
          <button type="button" className={styles.secondaryButton} onClick={handleExportJsModule}>
            Export JS module
          </button>
          <input
            id={fileInputId}
            type="file"
            accept="application/json"
            style={{ display: 'none' }}
            onChange={(e) => {
              const f = e.target.files?.[0];
              if (f) handleImportJson(f);
              e.currentTarget.value = '';
            }}
          />
          <button
            type="button"
            className={styles.primaryButton}
            onClick={() => document.getElementById(fileInputId)?.click()}
          >
            Import JSON
          </button>
        </div>
      </div>

      <div className={styles.panelCard}>
        <h2 className={styles.panelTitle}>Account</h2>
        <p className={styles.panelDescription}>
          Update the admin password stored locally in your browser. Anyone with this password can access the backend on this
          device.
        </p>
        <form className={styles.fieldGrid} onSubmit={handlePasswordSubmit}>
          <div className={styles.fieldGroup}>
            <label htmlFor="admin-new-password">New password</label>
            <input
              id="admin-new-password"
              type="password"
              value={password}
              onChange={(event) => setPasswordInput(event.target.value)}
              placeholder="Choose a new password"
              required
            />
          </div>
          {passwordSaved ? <p className={styles.note}>Password updated. Remember to save it somewhere safe.</p> : null}
          <div className={styles.buttonRow}>
            <button type="submit" className={styles.secondaryButton}>
              Update password
            </button>
          </div>
        </form>
      </div>
    </section>
  );
};

export default AdminPanel;
